# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 495)
        MainWindow.setMinimumSize(QtCore.QSize(942, 495))
        MainWindow.setMaximumSize(QtCore.QSize(942, 495))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMinimumSize(QtCore.QSize(0, 36))
        self.header.setMaximumSize(QtCore.QSize(16777215, 36))
        self.header.setStyleSheet("background-color: rgb(137, 213, 194)")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.label_3 = QtWidgets.QLabel(self.header)
        self.label_3.setGeometry(QtCore.QRect(10, 5, 81, 31))
        self.label_3.setStyleSheet("background: transparent")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.header)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(168, 242, 223, 255), stop:1 rgba(255, 255, 255, 255))")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.launchbtn = QtWidgets.QPushButton(self.frame)
        self.launchbtn.setGeometry(QtCore.QRect(482, 112, 191, 41))
        self.launchbtn.setMinimumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.launchbtn.setFont(font)
        self.launchbtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(27, 185, 146);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(31, 211, 166);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(22, 154, 121)\n"
"}")
        self.launchbtn.setAutoDefault(True)
        self.launchbtn.setFlat(False)
        self.launchbtn.setObjectName("launchbtn")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(440, 50, 3, 301))
        self.widget.setMinimumSize(QtCore.QSize(3, 301))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("background-color: rgb(137, 213, 194)")
        self.widget.setObjectName("widget")
        self.recordsbtn = QtWidgets.QPushButton(self.frame)
        self.recordsbtn.setGeometry(QtCore.QRect(710, 112, 191, 41))
        self.recordsbtn.setMinimumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.recordsbtn.setFont(font)
        self.recordsbtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(27, 185, 146);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(31, 211, 166);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(22, 154, 121)\n"
"}")
        self.recordsbtn.setAutoDefault(True)
        self.recordsbtn.setFlat(False)
        self.recordsbtn.setObjectName("recordsbtn")
        self.registerbtn = QtWidgets.QPushButton(self.frame)
        self.registerbtn.setGeometry(QtCore.QRect(482, 172, 191, 41))
        self.registerbtn.setMinimumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.registerbtn.setFont(font)
        self.registerbtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(27, 185, 146);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(31, 211, 166);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(22, 154, 121)\n"
"}")
        self.registerbtn.setAutoDefault(True)
        self.registerbtn.setFlat(False)
        self.registerbtn.setObjectName("registerbtn")
        self.logsbtn = QtWidgets.QPushButton(self.frame)
        self.logsbtn.setGeometry(QtCore.QRect(710, 172, 191, 41))
        self.logsbtn.setMinimumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.logsbtn.setFont(font)
        self.logsbtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(27, 185, 146);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(31, 211, 166);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(22, 154, 121)\n"
"}")
        self.logsbtn.setAutoDefault(True)
        self.logsbtn.setFlat(False)
        self.logsbtn.setObjectName("logsbtn")
        self.getstartedbtn = QtWidgets.QPushButton(self.frame)
        self.getstartedbtn.setGeometry(QtCore.QRect(481, 249, 421, 41))
        self.getstartedbtn.setMinimumSize(QtCore.QSize(421, 41))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.getstartedbtn.setFont(font)
        self.getstartedbtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(33, 113, 93);\n"
"    border: none;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(46, 159, 131);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(29, 100, 82);\n"
"}")
        self.getstartedbtn.setAutoDefault(True)
        self.getstartedbtn.setFlat(False)
        self.getstartedbtn.setObjectName("getstartedbtn")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(160, 220, 151, 71))
        self.label_2.setMinimumSize(QtCore.QSize(151, 71))
        font = QtGui.QFont()
        font.setFamily("Work Sans SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: transparent")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 130, 241, 101))
        self.label.setStyleSheet("background: transparent")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setMinimumSize(QtCore.QSize(0, 36))
        self.footer.setMaximumSize(QtCore.QSize(16777215, 36))
        self.footer.setStyleSheet("background-color: rgb(137, 213, 194)")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.trademark = QtWidgets.QLabel(self.footer)
        self.trademark.setGeometry(QtCore.QRect(340, -20, 251, 71))
        self.trademark.setMinimumSize(QtCore.QSize(151, 71))
        font = QtGui.QFont()
        font.setFamily("Work Sans SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.trademark.setFont(font)
        self.trademark.setStyleSheet("background: transparent")
        self.trademark.setAlignment(QtCore.Qt.AlignCenter)
        self.trademark.setObjectName("trademark")
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.launchbtn.setText(_translate("MainWindow", "LAUNCH"))
        self.recordsbtn.setText(_translate("MainWindow", "RECORDS"))
        self.registerbtn.setText(_translate("MainWindow", "REGISTER A FACE"))
        self.logsbtn.setText(_translate("MainWindow", "LOGS"))
        self.getstartedbtn.setText(_translate("MainWindow", "GET STARTED"))
        self.label_2.setText(_translate("MainWindow", "Mandate Safety, \n"
"Mandate Mask."))
        self.trademark.setText(_translate("MainWindow", "Powered by CloverByte, 2021"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
